server:
port: 9191

spring:
application:
name: APIGATEWAY
cloud::
gateway:
routes:
- id: BOOKING-SERVICE
uri: lb://BOOKING-SERVICE
predicates:
  - Path=/hotel/**

- id: PAYMENT-SERVICE
uri: lb://PAYMENT-SERVICE
predicates:
  - Path=/payment/**

discovery:
enabled: true

eureka:
instance:
hostname: localhost
